apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k2rj4jt2r-nodejs-gitops
  description: This is GitOps manifest for k2rj4jt2r-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=k2rj4jt2r-nodejs
    backstage.io/kubernetes-id: k2rj4jt2r-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: k2rj4jt2r-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:k2rj4jt2r-nodejs
