apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k2rj4jt2r-nodejs
  janus-idp.io/tekton: k2rj4jt2r-nodejs
  backstage.io/kubernetes-id: k2rj4jt2r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2rj4jt2r-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
